import { SELF } from 'cloudflare:test'
import { describe, expect, it } from 'vitest'

describe('[CF] OpenAPI documentation', () => {
  it('publishes the generated control-plane OpenAPI document', async () => {
    const res = await SELF.fetch('https://example.com/api/openapi.json')

    expect(res.status).toBe(200)
    const doc = (await res.json()) as {
      openapi: string
      paths: Record<
        string,
        Record<string, { operationId?: string; security?: unknown; parameters?: unknown[]; responses?: unknown }>
      >
      components?: { schemas?: Record<string, unknown>; securitySchemes?: Record<string, unknown> }
    }

    expect(doc.openapi).toBe('3.0.0')
    expect(doc.paths).toHaveProperty('/api/health')
    expect(doc.paths).toHaveProperty('/api/auth/login')
    expect(doc.paths).toHaveProperty('/api/auth/callback')
    expect(doc.paths).toHaveProperty('/api/auth/logout')
    expect(doc.paths).toHaveProperty('/api/auth/me')
    expect(doc.paths).toHaveProperty('/api/agents')
    expect(doc.paths).toHaveProperty('/api/agents/{agentId}')
    expect(doc.paths).toHaveProperty('/api/agents/{agentId}/versions')
    expect(doc.paths).toHaveProperty('/api/agents/{agentId}/sessions')
    expect(doc.paths).toHaveProperty('/api/environments')
    expect(doc.paths).toHaveProperty('/api/environments/{environmentId}')
    expect(doc.paths).toHaveProperty('/api/environments/{environmentId}/versions')
    expect(doc.paths).toHaveProperty('/api/sessions')
    expect(doc.paths).toHaveProperty('/api/sessions/{sessionId}')
    expect(doc.paths).toHaveProperty('/api/sessions/{sessionId}/stop')
    expect(doc.paths).toHaveProperty('/api/sessions/{sessionId}/reconnect')
    expect(doc.paths).toHaveProperty('/api/sessions/{sessionId}/events')
    expect(doc.paths).toHaveProperty('/api/vaults')
    expect(doc.paths).toHaveProperty('/api/vaults/{vaultId}')
    expect(doc.paths).toHaveProperty('/api/vaults/{vaultId}/credentials')
    expect(doc.paths).toHaveProperty('/api/vaults/{vaultId}/credentials/{credentialId}')
    expect(doc.paths).toHaveProperty('/api/vaults/{vaultId}/credentials/{credentialId}/versions')
    expect(doc.paths).toHaveProperty('/api/vaults/{vaultId}/credentials/{credentialId}/versions/{versionId}')
    expect(doc.paths['/api/sessions']).toHaveProperty('get')
    expect(doc.paths['/api/sessions']).toHaveProperty('post')
    expect(doc.paths['/api/sessions/{sessionId}']).toHaveProperty('get')
    expect(doc.paths['/api/sessions/{sessionId}']).toHaveProperty('patch')
    expect(doc.paths['/api/sessions/{sessionId}']).toHaveProperty('delete')
    expect(doc.paths['/api/sessions/{sessionId}/stop']).toHaveProperty('post')
    expect(doc.paths['/api/sessions/{sessionId}/reconnect']).toHaveProperty('get')
    expect(doc.paths['/api/sessions/{sessionId}/events']).toHaveProperty('get')
    expect(doc.paths['/api/vaults']).toHaveProperty('get')
    expect(doc.paths['/api/vaults']).toHaveProperty('post')
    expect(doc.paths['/api/vaults/{vaultId}']).toHaveProperty('get')
    expect(doc.paths['/api/vaults/{vaultId}']).toHaveProperty('patch')
    expect(doc.paths['/api/vaults/{vaultId}']).toHaveProperty('delete')
    expect(doc.paths['/api/vaults/{vaultId}/credentials']).toHaveProperty('get')
    expect(doc.paths['/api/vaults/{vaultId}/credentials']).toHaveProperty('post')
    expect(doc.paths['/api/vaults/{vaultId}/credentials/{credentialId}']).toHaveProperty('get')
    expect(doc.paths['/api/vaults/{vaultId}/credentials/{credentialId}']).toHaveProperty('patch')
    expect(doc.paths['/api/vaults/{vaultId}/credentials/{credentialId}/versions']).toHaveProperty('get')
    expect(doc.paths['/api/vaults/{vaultId}/credentials/{credentialId}/versions']).toHaveProperty('post')
    expect(doc.paths['/api/vaults/{vaultId}/credentials/{credentialId}/versions/{versionId}']).toHaveProperty('delete')
    expect(doc.paths['/api/health'].get.security).toBeUndefined()
    expect(doc.paths['/api/auth/login'].get.security).toBeUndefined()
    expect(doc.paths['/api/agents'].get.security).toEqual([{ cookieAuth: [] }])
    expect(doc.paths['/api/environments'].get.security).toEqual([{ cookieAuth: [] }])
    expect(doc.paths['/api/sessions'].get.security).toEqual([{ cookieAuth: [] }])
    expect(doc.paths['/api/vaults'].get.security).toEqual([{ cookieAuth: [] }])
    expect(doc.paths['/api/agents'].get.operationId).toBe('listAgents')
    expect(doc.paths['/api/environments'].get.operationId).toBe('listEnvironments')
    expect(doc.paths['/api/sessions'].get.operationId).toBe('listSessions')
    expect(doc.paths['/api/vaults'].get.operationId).toBe('listVaults')
    expect(doc.paths['/api/agents'].get.parameters?.map((parameter) => (parameter as { name?: string }).name)).toEqual(
      expect.arrayContaining(['includeArchived', 'status', 'search', 'createdFrom', 'createdTo', 'limit', 'cursor']),
    )
    expect(doc.components?.securitySchemes).toHaveProperty('cookieAuth')
    expect(doc.components?.schemas).toHaveProperty('AuthContext')
    expect(doc.components?.schemas).toHaveProperty('ErrorResponse')
    expect(doc.components?.schemas).toHaveProperty('ListPagination')
    expect(doc.components?.schemas).toHaveProperty('AgentListResponse')
    expect(doc.components?.schemas).toHaveProperty('EnvironmentListResponse')
    expect(doc.components?.schemas).toHaveProperty('SessionListResponse')
    expect(doc.components?.schemas).toHaveProperty('VaultListResponse')
    expect(doc.components?.schemas).toHaveProperty('VaultCredentialListResponse')
    expect(doc.components?.schemas).toHaveProperty('VaultCredentialVersionListResponse')
    expect(doc.components?.schemas).toHaveProperty('CreateAgentRequest')
    expect(doc.components?.schemas).toHaveProperty('UpdateAgentRequest')
    expect(doc.components?.schemas).toHaveProperty('Agent')
    expect(doc.components?.schemas).toHaveProperty('AgentVersion')
    expect(doc.components?.schemas).toHaveProperty('CreateEnvironmentRequest')
    expect(doc.components?.schemas).toHaveProperty('UpdateEnvironmentRequest')
    expect(doc.components?.schemas).toHaveProperty('Environment')
    expect(doc.components?.schemas).toHaveProperty('EnvironmentVersion')
    expect(doc.components?.schemas).toHaveProperty('Session')
    expect(doc.components?.schemas).toHaveProperty('Vault')
    expect(doc.components?.schemas).toHaveProperty('VaultCredential')
    expect(doc.components?.schemas).toHaveProperty('VaultCredentialVersion')
    expect(doc.components?.schemas).toHaveProperty('CreateVaultRequest')
    expect(doc.components?.schemas).toHaveProperty('CreateVaultCredentialRequest')
    expect(doc.components?.schemas).toHaveProperty('RotateVaultCredentialRequest')
  })

  it('serves interactive API docs', async () => {
    const res = await SELF.fetch('https://example.com/api/docs')

    expect(res.status).toBe(200)
    expect(res.headers.get('content-type')).toContain('text/html')
    expect(await res.text()).toContain('/api/openapi.json')
  })
})
