# Code generated by pnpm run openapi:generate; DO NOT EDIT.

OPERATIONS = [
  {
    "method": "GET",
    "path": "/api/v1/leases/{leaseId}/channel",
    "operationId": "connectLeaseSessionChannel",
    "summary": "Open a claimed runner session WebSocket channel",
    "tags": [
      "Leases"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/agents",
    "operationId": "createAgent",
    "summary": "Create an agent",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/auth/sessions",
    "operationId": "createAuthSession",
    "summary": "Complete OIDC sign-in and create an httpOnly session cookie",
    "tags": [
      "Auth"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/budgets",
    "operationId": "createBudget",
    "summary": "Create a budget",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/connections",
    "operationId": "createConnection",
    "summary": "Create a connector connection",
    "tags": [
      "Connections"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/environments",
    "operationId": "createEnvironment",
    "summary": "Create an environment",
    "tags": [
      "Environments"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/auth/federated-tenants",
    "operationId": "createFederatedTenant",
    "summary": "Authorize an external issuer tenant for the current project",
    "tags": [
      "Auth"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/leases",
    "operationId": "createLease",
    "summary": "Claim a specific available work item for a runner",
    "tags": [
      "Leases"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/policies",
    "operationId": "createPolicy",
    "summary": "Create a scoped governance policy",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/projects",
    "operationId": "createProject",
    "summary": "Create a project in the current organization",
    "tags": [
      "Projects"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/runners",
    "operationId": "createRunner",
    "summary": "Register a self-hosted runner",
    "tags": [
      "Runners"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/sessions",
    "operationId": "createSession",
    "summary": "Create a session",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/sessions/{sessionId}/events",
    "operationId": "createSessionEvents",
    "summary": "Batch-create session events",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/sessions/{sessionId}/messages",
    "operationId": "createSessionMessage",
    "summary": "Send a prompt message to a session",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/connections/{connectionId}/tools/{toolName}/calls",
    "operationId": "createToolCall",
    "summary": "Execute a connection tool through the AMA policy boundary",
    "tags": [
      "Connections"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/triggers",
    "operationId": "createTrigger",
    "summary": "Create a trigger",
    "tags": [
      "Triggers"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/vaults",
    "operationId": "createVault",
    "summary": "Create a vault",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/vaults/{vaultId}/credentials",
    "operationId": "createVaultCredential",
    "summary": "Create vault credential metadata",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/vaults/{vaultId}/credentials/{credentialId}/versions",
    "operationId": "createVaultCredentialVersion",
    "summary": "Rotate a vault credential by creating a new version",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/v1/sessions/{sessionId}/approvals/{approvalId}",
    "operationId": "decideSessionApproval",
    "summary": "Approve or deny a pending tool call",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "DELETE",
    "path": "/api/v1/budgets/{budgetId}",
    "operationId": "deleteBudget",
    "summary": "Delete a budget",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "DELETE",
    "path": "/api/v1/auth/sessions/current",
    "operationId": "deleteCurrentAuthSession",
    "summary": "Sign out and clear the session cookie",
    "tags": [
      "Auth"
    ]
  },
  {
    "method": "DELETE",
    "path": "/api/v1/auth/federated-tenants/{tenantId}",
    "operationId": "deleteFederatedTenant",
    "summary": "Delete a federated tenant",
    "tags": [
      "Auth"
    ]
  },
  {
    "method": "DELETE",
    "path": "/api/v1/policies/{policyId}",
    "operationId": "deletePolicy",
    "summary": "Delete a governance policy",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "DELETE",
    "path": "/api/v1/vaults/{vaultId}/credentials/{credentialId}/versions/{versionId}",
    "operationId": "deleteVaultCredentialVersion",
    "summary": "Delete an unused vault credential version",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/health",
    "operationId": "getHealth",
    "summary": "Get Worker health",
    "tags": [
      "System"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/agents/{agentId}/handoff-candidates",
    "operationId": "listAgentHandoffCandidates",
    "summary": "List handoff candidate agents",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/agents",
    "operationId": "listAgents",
    "summary": "List agents",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/agents/{agentId}/versions",
    "operationId": "listAgentVersions",
    "summary": "List agent versions",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/audit-records",
    "operationId": "listAuditRecords",
    "summary": "List audit records",
    "tags": [
      "Audit"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/budgets",
    "operationId": "listBudgets",
    "summary": "List budgets",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/connections",
    "operationId": "listConnections",
    "summary": "List connections",
    "tags": [
      "Connections"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/connections/{connectionId}/tools",
    "operationId": "listConnectionTools",
    "summary": "List connection tools",
    "tags": [
      "Connections"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/connectors",
    "operationId": "listConnectors",
    "summary": "List connectors",
    "tags": [
      "Connectors"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/environments",
    "operationId": "listEnvironments",
    "summary": "List environments",
    "tags": [
      "Environments"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/environments/{environmentId}/versions",
    "operationId": "listEnvironmentVersions",
    "summary": "List environment versions",
    "tags": [
      "Environments"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/auth/federated-tenants",
    "operationId": "listFederatedTenants",
    "summary": "List federated tenants for the current project",
    "tags": [
      "Auth"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/leases",
    "operationId": "listLeases",
    "summary": "List work leases",
    "tags": [
      "Leases"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/providers/models",
    "operationId": "listModels",
    "summary": "List all catalog models",
    "tags": [
      "Providers"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/policies",
    "operationId": "listPolicies",
    "summary": "List scoped governance policies",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/projects",
    "operationId": "listProjects",
    "summary": "List projects in the current organization",
    "tags": [
      "Projects"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/providers/{providerId}/models",
    "operationId": "listProviderModels",
    "summary": "List a vendor's models",
    "tags": [
      "Providers"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/providers",
    "operationId": "listProviders",
    "summary": "List model vendors",
    "tags": [
      "Providers"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/runners",
    "operationId": "listRunners",
    "summary": "List self-hosted runners",
    "tags": [
      "Runners"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/sessions/{sessionId}/approvals",
    "operationId": "listSessionApprovals",
    "summary": "List tool approvals for a session",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/sessions/{sessionId}/events",
    "operationId": "listSessionEvents",
    "summary": "List session events",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/sessions/{sessionId}/messages",
    "operationId": "listSessionMessages",
    "summary": "List session messages",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/sessions",
    "operationId": "listSessions",
    "summary": "List sessions",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/connections/{connectionId}/tools/{toolName}/calls",
    "operationId": "listToolCalls",
    "summary": "List tool calls",
    "tags": [
      "Connections"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/triggers/{triggerId}/runs",
    "operationId": "listTriggerRuns",
    "summary": "List trigger runs",
    "tags": [
      "Triggers"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/triggers",
    "operationId": "listTriggers",
    "summary": "List triggers",
    "tags": [
      "Triggers"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/usage-records",
    "operationId": "listUsageRecords",
    "summary": "List usage records",
    "tags": [
      "Usage"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/vaults/{vaultId}/credentials",
    "operationId": "listVaultCredentials",
    "summary": "List vault credential metadata",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/vaults/{vaultId}/credentials/{credentialId}/versions",
    "operationId": "listVaultCredentialVersions",
    "summary": "List vault credential versions",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/vaults",
    "operationId": "listVaults",
    "summary": "List vaults",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/work-items",
    "operationId": "listWorkItems",
    "summary": "List queued self-hosted work items",
    "tags": [
      "Work items"
    ]
  },
  {
    "method": "PUT",
    "path": "/api/v1/runners/{runnerId}/heartbeat",
    "operationId": "putRunnerHeartbeat",
    "summary": "Replace the current runner heartbeat state",
    "tags": [
      "Runners"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/agents/{agentId}",
    "operationId": "readAgent",
    "summary": "Read an agent",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/agents/{agentId}/memory",
    "operationId": "readAgentMemory",
    "summary": "Read agent memory",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/agents/{agentId}/versions/{version}",
    "operationId": "readAgentVersion",
    "summary": "Read an agent version",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/audit-records/{recordId}",
    "operationId": "readAuditRecord",
    "summary": "Read an audit record",
    "tags": [
      "Audit"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/auth/config",
    "operationId": "readAuthConfig",
    "summary": "Discover available sign-in methods for an organization",
    "tags": [
      "Auth"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/budgets/{budgetId}",
    "operationId": "readBudget",
    "summary": "Read a budget",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/connections/{connectionId}",
    "operationId": "readConnection",
    "summary": "Read connection",
    "tags": [
      "Connections"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/connectors/{connectorId}",
    "operationId": "readConnector",
    "summary": "Read connector",
    "tags": [
      "Connectors"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/auth/sessions/current",
    "operationId": "readCurrentAuthSession",
    "summary": "Read the authenticated session context",
    "tags": [
      "Auth"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/effective-policy",
    "operationId": "readEffectivePolicy",
    "summary": "Read the effective governance policy",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/environments/{environmentId}",
    "operationId": "readEnvironment",
    "summary": "Read an environment",
    "tags": [
      "Environments"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/environments/{environmentId}/versions/{version}",
    "operationId": "readEnvironmentVersion",
    "summary": "Read an environment version",
    "tags": [
      "Environments"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/auth/federated-tenants/{tenantId}",
    "operationId": "readFederatedTenant",
    "summary": "Read a federated tenant",
    "tags": [
      "Auth"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/leases/{leaseId}",
    "operationId": "readLease",
    "summary": "Read a work lease",
    "tags": [
      "Leases"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/policies/{policyId}",
    "operationId": "readPolicy",
    "summary": "Read a governance policy",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/projects/{projectId}",
    "operationId": "readProject",
    "summary": "Read a single project",
    "tags": [
      "Projects"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/providers/{providerId}",
    "operationId": "readProvider",
    "summary": "Read a model vendor",
    "tags": [
      "Providers"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/runners/{runnerId}",
    "operationId": "readRunner",
    "summary": "Read a self-hosted runner",
    "tags": [
      "Runners"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/runners/{runnerId}/heartbeat",
    "operationId": "readRunnerHeartbeat",
    "summary": "Read the current runner heartbeat state",
    "tags": [
      "Runners"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/sessions/{sessionId}",
    "operationId": "readSession",
    "summary": "Read a session",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/sessions/{sessionId}/approvals/{approvalId}",
    "operationId": "readSessionApproval",
    "summary": "Read a tool approval",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/sessions/{sessionId}/connection",
    "operationId": "readSessionConnection",
    "summary": "Read session runtime connection details",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/sessions/{sessionId}/messages/{messageId}",
    "operationId": "readSessionMessage",
    "summary": "Read a session message delivery state",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/connections/{connectionId}/tools/{toolName}/calls/{callId}",
    "operationId": "readToolCall",
    "summary": "Read tool call",
    "tags": [
      "Connections"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/triggers/{triggerId}",
    "operationId": "readTrigger",
    "summary": "Read a trigger",
    "tags": [
      "Triggers"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/triggers/{triggerId}/runs/{runId}",
    "operationId": "readTriggerRun",
    "summary": "Read a trigger run",
    "tags": [
      "Triggers"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/usage-records/{recordId}",
    "operationId": "readUsageRecord",
    "summary": "Read a usage record",
    "tags": [
      "Usage"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/usage-summary",
    "operationId": "readUsageSummary",
    "summary": "Read aggregated usage",
    "tags": [
      "Usage"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/vaults/{vaultId}",
    "operationId": "readVault",
    "summary": "Read a vault",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/vaults/{vaultId}/credentials/{credentialId}",
    "operationId": "readVaultCredential",
    "summary": "Read vault credential metadata",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/vaults/{vaultId}/credentials/{credentialId}/versions/{versionId}",
    "operationId": "readVaultCredentialVersion",
    "summary": "Read a vault credential version",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "GET",
    "path": "/api/v1/work-items/{workItemId}",
    "operationId": "readWorkItem",
    "summary": "Read a queued self-hosted work item",
    "tags": [
      "Work items"
    ]
  },
  {
    "method": "POST",
    "path": "/api/v1/providers/refresh",
    "operationId": "refreshCatalog",
    "summary": "Refresh the model catalog",
    "tags": [
      "Providers"
    ]
  },
  {
    "method": "PUT",
    "path": "/api/v1/agents/{agentId}/memory",
    "operationId": "replaceAgentMemory",
    "summary": "Replace agent memory",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "PUT",
    "path": "/api/v1/policies/{policyId}",
    "operationId": "replacePolicy",
    "summary": "Replace a governance policy",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/v1/agents/{agentId}",
    "operationId": "updateAgent",
    "summary": "Update an agent",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/v1/budgets/{budgetId}",
    "operationId": "updateBudget",
    "summary": "Update a budget",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/v1/connections/{connectionId}",
    "operationId": "updateConnection",
    "summary": "Update connection state, credential, or settings",
    "tags": [
      "Connections"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/v1/environments/{environmentId}",
    "operationId": "updateEnvironment",
    "summary": "Update an environment",
    "tags": [
      "Environments"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/v1/auth/federated-tenants/{tenantId}",
    "operationId": "updateFederatedTenant",
    "summary": "Update a federated tenant",
    "tags": [
      "Auth"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/v1/leases/{leaseId}",
    "operationId": "updateLease",
    "summary": "Renew or finish a work lease",
    "tags": [
      "Leases"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/v1/runners/{runnerId}",
    "operationId": "updateRunner",
    "summary": "Update or archive a self-hosted runner",
    "tags": [
      "Runners"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/v1/sessions/{sessionId}",
    "operationId": "updateSession",
    "summary": "Update a session",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/v1/triggers/{triggerId}",
    "operationId": "updateTrigger",
    "summary": "Update, pause, or archive a trigger",
    "tags": [
      "Triggers"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/v1/vaults/{vaultId}",
    "operationId": "updateVault",
    "summary": "Update or archive a vault",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/v1/vaults/{vaultId}/credentials/{credentialId}",
    "operationId": "updateVaultCredential",
    "summary": "Update or revoke vault credential metadata",
    "tags": [
      "Vaults"
    ]
  }
]
