# Code generated by pnpm run openapi:generate; DO NOT EDIT.

OPERATIONS = [
  {
    "method": "POST",
    "path": "/api/governance/config",
    "operationId": "applyGovernanceConfig",
    "summary": "Apply declarative governance config atomically",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "DELETE",
    "path": "/api/agents/{agentId}",
    "operationId": "archiveAgent",
    "summary": "Archive an agent",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "DELETE",
    "path": "/api/environments/{environmentId}",
    "operationId": "archiveEnvironment",
    "summary": "Archive an environment",
    "tags": [
      "Environments"
    ]
  },
  {
    "method": "DELETE",
    "path": "/api/scheduled-agent-triggers/{triggerId}",
    "operationId": "archiveScheduledAgentTrigger",
    "summary": "Archive a scheduled agent trigger",
    "tags": [
      "Scheduled agent triggers"
    ]
  },
  {
    "method": "DELETE",
    "path": "/api/sessions/{sessionId}",
    "operationId": "archiveSession",
    "summary": "Archive a session",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "DELETE",
    "path": "/api/vaults/{vaultId}",
    "operationId": "archiveVault",
    "summary": "Archive a vault",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "POST",
    "path": "/api/mcp/connections/{connectionId}/tools/{toolName}/calls",
    "operationId": "callMcpTool",
    "summary": "Call MCP tool through AMA policy boundary",
    "tags": [
      "MCP"
    ]
  },
  {
    "method": "POST",
    "path": "/api/mcp/connections",
    "operationId": "connectMcpConnector",
    "summary": "Connect or upsert an MCP connector",
    "tags": [
      "MCP"
    ]
  },
  {
    "method": "GET",
    "path": "/api/runners/{runnerId}/leases/{leaseId}/channel",
    "operationId": "connectRunnerSessionChannel",
    "summary": "Open a claimed runner session WebSocket channel",
    "tags": [
      "Runner leases"
    ]
  },
  {
    "method": "POST",
    "path": "/api/agents",
    "operationId": "createAgent",
    "summary": "Create an agent",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "POST",
    "path": "/api/auth/session",
    "operationId": "createAuthSession",
    "summary": "Complete OIDC sign-in and create an httpOnly session cookie",
    "tags": [
      "Auth"
    ]
  },
  {
    "method": "POST",
    "path": "/api/governance/budgets",
    "operationId": "createBudget",
    "summary": "Create budget",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "POST",
    "path": "/api/environments",
    "operationId": "createEnvironment",
    "summary": "Create an environment",
    "tags": [
      "Environments"
    ]
  },
  {
    "method": "POST",
    "path": "/api/projects/{projectId}/external-bindings",
    "operationId": "createExternalProjectBinding",
    "summary": "Bind an external issuer tenant to a project",
    "tags": [
      "Projects"
    ]
  },
  {
    "method": "POST",
    "path": "/api/projects",
    "operationId": "createProject",
    "summary": "Create a project in the current organization",
    "tags": [
      "Projects"
    ]
  },
  {
    "method": "POST",
    "path": "/api/providers",
    "operationId": "createProvider",
    "summary": "Create a provider",
    "tags": [
      "Providers"
    ]
  },
  {
    "method": "POST",
    "path": "/api/governance/provider-access-rules",
    "operationId": "createProviderAccessRule",
    "summary": "Create provider access rule",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "POST",
    "path": "/api/runners",
    "operationId": "createRunner",
    "summary": "Register a self-hosted runner",
    "tags": [
      "Runners"
    ]
  },
  {
    "method": "POST",
    "path": "/api/runners/{runnerId}/heartbeats",
    "operationId": "createRunnerHeartbeat",
    "summary": "Record a runner heartbeat",
    "tags": [
      "Runners"
    ]
  },
  {
    "method": "POST",
    "path": "/api/runners/{runnerId}/leases",
    "operationId": "createRunnerLease",
    "summary": "Claim queued self-hosted runner work",
    "tags": [
      "Runner leases"
    ]
  },
  {
    "method": "POST",
    "path": "/api/runners/{runnerId}/leases/{leaseId}/events",
    "operationId": "createRunnerLeaseEvents",
    "summary": "Upload structured runner lease events",
    "tags": [
      "Runner leases"
    ]
  },
  {
    "method": "POST",
    "path": "/api/scheduled-agent-triggers",
    "operationId": "createScheduledAgentTrigger",
    "summary": "Create a scheduled agent trigger",
    "tags": [
      "Scheduled agent triggers"
    ]
  },
  {
    "method": "POST",
    "path": "/api/sessions",
    "operationId": "createSession",
    "summary": "Create a session",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "POST",
    "path": "/api/sessions/{sessionId}/commands",
    "operationId": "createSessionCommand",
    "summary": "Send a command to an active session",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "POST",
    "path": "/api/vaults",
    "operationId": "createVault",
    "summary": "Create a vault",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "POST",
    "path": "/api/vaults/{vaultId}/credentials",
    "operationId": "createVaultCredential",
    "summary": "Create vault credential metadata",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "POST",
    "path": "/api/sessions/{sessionId}/approvals/{approvalId}",
    "operationId": "decideSessionApproval",
    "summary": "Approve or deny a pending tool call",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "DELETE",
    "path": "/api/providers/{providerId}",
    "operationId": "deleteProvider",
    "summary": "Delete a provider",
    "tags": [
      "Providers"
    ]
  },
  {
    "method": "DELETE",
    "path": "/api/vaults/{vaultId}/credentials/{credentialId}/versions/{versionId}",
    "operationId": "deleteVaultCredentialVersion",
    "summary": "Delete unused vault credential version metadata",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "DELETE",
    "path": "/api/mcp/connections/{connectionId}",
    "operationId": "disconnectMcpConnection",
    "summary": "Disconnect MCP connection",
    "tags": [
      "MCP"
    ]
  },
  {
    "method": "POST",
    "path": "/api/providers/{providerId}/models/discovery",
    "operationId": "discoverProviderModels",
    "summary": "Discover provider models",
    "tags": [
      "Providers"
    ]
  },
  {
    "method": "POST",
    "path": "/api/governance/evaluations",
    "operationId": "evaluateGovernancePolicy",
    "summary": "Evaluate governance policy",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "GET",
    "path": "/api/audit-records/export",
    "operationId": "exportAuditRecords",
    "summary": "Export audit records",
    "tags": [
      "Audit"
    ]
  },
  {
    "method": "GET",
    "path": "/api/sessions/{sessionId}/events/export",
    "operationId": "exportSessionEvents",
    "summary": "Export session events as NDJSON",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "GET",
    "path": "/api/usage/export",
    "operationId": "exportUsageSummary",
    "summary": "Export usage summaries",
    "tags": [
      "Usage"
    ]
  },
  {
    "method": "GET",
    "path": "/api/health",
    "operationId": "getHealth",
    "summary": "Get Worker health",
    "tags": [
      "System"
    ]
  },
  {
    "method": "GET",
    "path": "/api/auth/login-options",
    "operationId": "getLoginOptions",
    "summary": "Discover available login methods for an organization",
    "tags": [
      "Auth"
    ]
  },
  {
    "method": "GET",
    "path": "/api/agents/{agentId}/handoff-candidates",
    "operationId": "listAgentHandoffCandidates",
    "summary": "List handoff candidate agents",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "GET",
    "path": "/api/agents",
    "operationId": "listAgents",
    "summary": "List agents",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "GET",
    "path": "/api/agents/{agentId}/versions",
    "operationId": "listAgentVersions",
    "summary": "List agent versions",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "GET",
    "path": "/api/audit-records",
    "operationId": "listAuditRecords",
    "summary": "List audit records",
    "tags": [
      "Audit"
    ]
  },
  {
    "method": "GET",
    "path": "/api/governance/budgets",
    "operationId": "listBudgets",
    "summary": "List budgets",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "GET",
    "path": "/api/environments",
    "operationId": "listEnvironments",
    "summary": "List environments",
    "tags": [
      "Environments"
    ]
  },
  {
    "method": "GET",
    "path": "/api/environments/{environmentId}/versions",
    "operationId": "listEnvironmentVersions",
    "summary": "List environment versions",
    "tags": [
      "Environments"
    ]
  },
  {
    "method": "GET",
    "path": "/api/projects/{projectId}/external-bindings",
    "operationId": "listExternalProjectBindings",
    "summary": "List external tenant bindings for a project",
    "tags": [
      "Projects"
    ]
  },
  {
    "method": "GET",
    "path": "/api/mcp/connections",
    "operationId": "listMcpConnections",
    "summary": "List MCP connections",
    "tags": [
      "MCP"
    ]
  },
  {
    "method": "GET",
    "path": "/api/mcp/connectors",
    "operationId": "listMcpConnectors",
    "summary": "List MCP connectors",
    "tags": [
      "MCP"
    ]
  },
  {
    "method": "GET",
    "path": "/api/mcp/connections/{connectionId}/tools",
    "operationId": "listMcpTools",
    "summary": "List MCP connection tools",
    "tags": [
      "MCP"
    ]
  },
  {
    "method": "GET",
    "path": "/api/projects",
    "operationId": "listProjects",
    "summary": "List projects in the current organization",
    "tags": [
      "Projects"
    ]
  },
  {
    "method": "GET",
    "path": "/api/governance/provider-access-rules",
    "operationId": "listProviderAccessRules",
    "summary": "List provider access rules",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "GET",
    "path": "/api/providers/{providerId}/models",
    "operationId": "listProviderModels",
    "summary": "List provider models",
    "tags": [
      "Providers"
    ]
  },
  {
    "method": "GET",
    "path": "/api/providers",
    "operationId": "listProviders",
    "summary": "List providers",
    "tags": [
      "Providers"
    ]
  },
  {
    "method": "GET",
    "path": "/api/runners",
    "operationId": "listRunners",
    "summary": "List self-hosted runners",
    "tags": [
      "Runners"
    ]
  },
  {
    "method": "GET",
    "path": "/api/runners/work-items",
    "operationId": "listRunnerWorkItems",
    "summary": "List self-hosted runner work items",
    "tags": [
      "Runner work"
    ]
  },
  {
    "method": "GET",
    "path": "/api/scheduled-agent-triggers",
    "operationId": "listScheduledAgentTriggers",
    "summary": "List scheduled agent triggers",
    "tags": [
      "Scheduled agent triggers"
    ]
  },
  {
    "method": "GET",
    "path": "/api/scheduled-agent-triggers/{triggerId}/runs",
    "operationId": "listScheduledTriggerRuns",
    "summary": "List scheduled trigger runs",
    "tags": [
      "Scheduled agent triggers"
    ]
  },
  {
    "method": "GET",
    "path": "/api/sessions/{sessionId}/approvals",
    "operationId": "listSessionApprovals",
    "summary": "List pending tool approvals for a session",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "GET",
    "path": "/api/sessions/{sessionId}/events",
    "operationId": "listSessionEvents",
    "summary": "List session events",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "GET",
    "path": "/api/sessions",
    "operationId": "listSessions",
    "summary": "List sessions",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "GET",
    "path": "/api/usage",
    "operationId": "listUsageRecords",
    "summary": "List usage records",
    "tags": [
      "Usage"
    ]
  },
  {
    "method": "GET",
    "path": "/api/vaults/{vaultId}/credentials",
    "operationId": "listVaultCredentials",
    "summary": "List vault credential metadata",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "GET",
    "path": "/api/vaults/{vaultId}/credentials/{credentialId}/versions",
    "operationId": "listVaultCredentialVersions",
    "summary": "List vault credential versions",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "GET",
    "path": "/api/vaults",
    "operationId": "listVaults",
    "summary": "List vaults",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "POST",
    "path": "/api/governance/config/preview",
    "operationId": "previewGovernanceConfig",
    "summary": "Preview declarative governance config impact",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "GET",
    "path": "/api/agents/{agentId}",
    "operationId": "readAgent",
    "summary": "Read an agent",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "GET",
    "path": "/api/agents/{agentId}/memory",
    "operationId": "readAgentMemory",
    "summary": "Read agent memory",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "GET",
    "path": "/api/audit-records/{recordId}",
    "operationId": "readAuditRecord",
    "summary": "Read an audit record",
    "tags": [
      "Audit"
    ]
  },
  {
    "method": "GET",
    "path": "/api/governance/effective-policy",
    "operationId": "readEffectiveGovernancePolicy",
    "summary": "Read effective governance policy",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "GET",
    "path": "/api/environments/{environmentId}",
    "operationId": "readEnvironment",
    "summary": "Read an environment",
    "tags": [
      "Environments"
    ]
  },
  {
    "method": "GET",
    "path": "/api/governance/policy",
    "operationId": "readGovernancePolicy",
    "summary": "Read governance policy",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "GET",
    "path": "/api/mcp/connections/{connectionId}",
    "operationId": "readMcpConnection",
    "summary": "Read MCP connection",
    "tags": [
      "MCP"
    ]
  },
  {
    "method": "GET",
    "path": "/api/mcp/connectors/{connectorId}",
    "operationId": "readMcpConnector",
    "summary": "Read MCP connector",
    "tags": [
      "MCP"
    ]
  },
  {
    "method": "GET",
    "path": "/api/providers/{providerId}",
    "operationId": "readProvider",
    "summary": "Read a provider",
    "tags": [
      "Providers"
    ]
  },
  {
    "method": "GET",
    "path": "/api/runners/{runnerId}",
    "operationId": "readRunner",
    "summary": "Read a self-hosted runner",
    "tags": [
      "Runners"
    ]
  },
  {
    "method": "GET",
    "path": "/api/scheduled-agent-triggers/{triggerId}",
    "operationId": "readScheduledAgentTrigger",
    "summary": "Read a scheduled agent trigger",
    "tags": [
      "Scheduled agent triggers"
    ]
  },
  {
    "method": "GET",
    "path": "/api/sessions/{sessionId}",
    "operationId": "readSession",
    "summary": "Read a session",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "GET",
    "path": "/api/sessions/{sessionId}/reconnect",
    "operationId": "readSessionReconnect",
    "summary": "Read reconnect metadata",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "GET",
    "path": "/api/usage/summary",
    "operationId": "readUsageSummary",
    "summary": "Read usage summary",
    "tags": [
      "Usage"
    ]
  },
  {
    "method": "GET",
    "path": "/api/vaults/{vaultId}",
    "operationId": "readVault",
    "summary": "Read a vault",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "GET",
    "path": "/api/vaults/{vaultId}/credentials/{credentialId}",
    "operationId": "readVaultCredential",
    "summary": "Read vault credential metadata",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "POST",
    "path": "/api/vaults/{vaultId}/credentials/{credentialId}/versions",
    "operationId": "rotateVaultCredential",
    "summary": "Rotate vault credential",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "POST",
    "path": "/api/sessions/{sessionId}/stop",
    "operationId": "stopSession",
    "summary": "Stop a session",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "GET",
    "path": "/api/sessions/{sessionId}/events/stream",
    "operationId": "streamSessionEvents",
    "summary": "Stream session events as NDJSON",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/agents/{agentId}",
    "operationId": "updateAgent",
    "summary": "Update an agent",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/agents/{agentId}/memory",
    "operationId": "updateAgentMemory",
    "summary": "Update agent memory",
    "tags": [
      "Agents"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/environments/{environmentId}",
    "operationId": "updateEnvironment",
    "summary": "Update an environment",
    "tags": [
      "Environments"
    ]
  },
  {
    "method": "PUT",
    "path": "/api/governance/policy",
    "operationId": "updateGovernancePolicy",
    "summary": "Update governance policy",
    "tags": [
      "Governance"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/mcp/connections/{connectionId}",
    "operationId": "updateMcpConnection",
    "summary": "Update MCP connection",
    "tags": [
      "MCP"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/providers/{providerId}",
    "operationId": "updateProvider",
    "summary": "Update a provider",
    "tags": [
      "Providers"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/runners/{runnerId}",
    "operationId": "updateRunner",
    "summary": "Update a self-hosted runner",
    "tags": [
      "Runners"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/runners/{runnerId}/leases/{leaseId}",
    "operationId": "updateRunnerLease",
    "summary": "Renew or finish a runner lease",
    "tags": [
      "Runner leases"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/scheduled-agent-triggers/{triggerId}",
    "operationId": "updateScheduledAgentTrigger",
    "summary": "Update a scheduled agent trigger",
    "tags": [
      "Scheduled agent triggers"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/sessions/{sessionId}",
    "operationId": "updateSession",
    "summary": "Update a session lifecycle state",
    "tags": [
      "Sessions"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/vaults/{vaultId}",
    "operationId": "updateVault",
    "summary": "Update a vault",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "PATCH",
    "path": "/api/vaults/{vaultId}/credentials/{credentialId}",
    "operationId": "updateVaultCredential",
    "summary": "Update or revoke vault credential metadata",
    "tags": [
      "Vaults"
    ]
  },
  {
    "method": "POST",
    "path": "/api/providers/{providerId}/models",
    "operationId": "upsertProviderModel",
    "summary": "Upsert provider model metadata",
    "tags": [
      "Providers"
    ]
  },
  {
    "method": "POST",
    "path": "/api/governance/config/validate",
    "operationId": "validateGovernanceConfig",
    "summary": "Validate declarative governance config",
    "tags": [
      "Governance"
    ]
  }
]
