// Code generated by `pnpm run contract:generate`; DO NOT EDIT.
//
// Canonical AMA session event types, single-sourced from
// shared/session-events.ts (AMA_SESSION_EVENT_DEFINITIONS).

package main

const (
	EventTypeAgentStart          = "agent_start"
	EventTypeAgentEnd            = "agent_end"
	EventTypeTurnStart           = "turn_start"
	EventTypeTurnEnd             = "turn_end"
	EventTypeSessionStop         = "session_stop"
	EventTypeSessionCheckpoint   = "session_checkpoint"
	EventTypeSessionResume       = "session_resume"
	EventTypeMessageStart        = "message_start"
	EventTypeMessageUpdate       = "message_update"
	EventTypeMessageEnd          = "message_end"
	EventTypeToolExecutionStart  = "tool_execution_start"
	EventTypeToolExecutionUpdate = "tool_execution_update"
	EventTypeToolExecutionEnd    = "tool_execution_end"
	EventTypeUsageRecorded       = "usage.recorded"
	EventTypePolicyDecision      = "policy.decision"
	EventTypePermissionRequest   = "permission.request"
	EventTypeRuntimeError        = "runtime.error"
	EventTypeRuntimeMetadata     = "runtime.metadata"
	EventTypeRuntimeOutput       = "runtime.output"
	EventTypeRunnerMetadata      = "runner.metadata"
)

// CanonicalEventTypes is the full ordered set of canonical event types.
var CanonicalEventTypes = []string{
	EventTypeAgentStart,
	EventTypeAgentEnd,
	EventTypeTurnStart,
	EventTypeTurnEnd,
	EventTypeSessionStop,
	EventTypeSessionCheckpoint,
	EventTypeSessionResume,
	EventTypeMessageStart,
	EventTypeMessageUpdate,
	EventTypeMessageEnd,
	EventTypeToolExecutionStart,
	EventTypeToolExecutionUpdate,
	EventTypeToolExecutionEnd,
	EventTypeUsageRecorded,
	EventTypePolicyDecision,
	EventTypePermissionRequest,
	EventTypeRuntimeError,
	EventTypeRuntimeMetadata,
	EventTypeRuntimeOutput,
	EventTypeRunnerMetadata,
}

// IsCanonicalEventType reports whether t is a known canonical event type.
func IsCanonicalEventType(t string) bool {
	for _, known := range CanonicalEventTypes {
		if known == t {
			return true
		}
	}
	return false
}
