// Package sessionevent provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package sessionevent

// Defines values for AmaSessionEventType.
const (
	EventTypeMessageCompleted    AmaSessionEventType = "message.completed"
	EventTypeMessageStarted      AmaSessionEventType = "message.started"
	EventTypeMessageUpdated      AmaSessionEventType = "message.updated"
	EventTypePermissionDenied    AmaSessionEventType = "permission.denied"
	EventTypePermissionRequested AmaSessionEventType = "permission.requested"
	EventTypePermissionResolved  AmaSessionEventType = "permission.resolved"
	EventTypeRuntimeCompleted    AmaSessionEventType = "runtime.completed"
	EventTypeRuntimeError        AmaSessionEventType = "runtime.error"
	EventTypeRuntimeStarted      AmaSessionEventType = "runtime.started"
	EventTypeTurnCompleted       AmaSessionEventType = "turn.completed"
	EventTypeTurnStarted         AmaSessionEventType = "turn.started"
	EventTypeUsageRecorded       AmaSessionEventType = "usage.recorded"
)

// Valid indicates whether the value is a known member of the AmaSessionEventType enum.
func (e AmaSessionEventType) Valid() bool {
	switch e {
	case EventTypeMessageCompleted:
		return true
	case EventTypeMessageStarted:
		return true
	case EventTypeMessageUpdated:
		return true
	case EventTypePermissionDenied:
		return true
	case EventTypePermissionRequested:
		return true
	case EventTypePermissionResolved:
		return true
	case EventTypeRuntimeCompleted:
		return true
	case EventTypeRuntimeError:
		return true
	case EventTypeRuntimeStarted:
		return true
	case EventTypeTurnCompleted:
		return true
	case EventTypeTurnStarted:
		return true
	case EventTypeUsageRecorded:
		return true
	default:
		return false
	}
}

// AmaSessionEventType defines model for AmaSessionEventType.
type AmaSessionEventType string
