// Package sessionevent provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package sessionevent

// Defines values for AmaSessionEventType.
const (
	EventTypeAgentCompleted      AmaSessionEventType = "agent.completed"
	EventTypeAgentStarted        AmaSessionEventType = "agent.started"
	EventTypeMessageCompleted    AmaSessionEventType = "message.completed"
	EventTypeMessageStarted      AmaSessionEventType = "message.started"
	EventTypeMessageUpdated      AmaSessionEventType = "message.updated"
	EventTypePermissionDenied    AmaSessionEventType = "permission.denied"
	EventTypePermissionRequested AmaSessionEventType = "permission.requested"
	EventTypePermissionResolved  AmaSessionEventType = "permission.resolved"
	EventTypeRunnerStatus        AmaSessionEventType = "runner.status"
	EventTypeRuntimeError        AmaSessionEventType = "runtime.error"
	EventTypeRuntimeOutput       AmaSessionEventType = "runtime.output"
	EventTypeRuntimeStatus       AmaSessionEventType = "runtime.status"
	EventTypeSessionCheckpointed AmaSessionEventType = "session.checkpointed"
	EventTypeSessionResumed      AmaSessionEventType = "session.resumed"
	EventTypeSessionStopped      AmaSessionEventType = "session.stopped"
	EventTypeToolCallCompleted   AmaSessionEventType = "tool_call.completed"
	EventTypeToolCallStarted     AmaSessionEventType = "tool_call.started"
	EventTypeToolCallUpdated     AmaSessionEventType = "tool_call.updated"
	EventTypeTurnCompleted       AmaSessionEventType = "turn.completed"
	EventTypeTurnStarted         AmaSessionEventType = "turn.started"
	EventTypeUsageRecorded       AmaSessionEventType = "usage.recorded"
)

// Valid indicates whether the value is a known member of the AmaSessionEventType enum.
func (e AmaSessionEventType) Valid() bool {
	switch e {
	case EventTypeAgentCompleted:
		return true
	case EventTypeAgentStarted:
		return true
	case EventTypeMessageCompleted:
		return true
	case EventTypeMessageStarted:
		return true
	case EventTypeMessageUpdated:
		return true
	case EventTypePermissionDenied:
		return true
	case EventTypePermissionRequested:
		return true
	case EventTypePermissionResolved:
		return true
	case EventTypeRunnerStatus:
		return true
	case EventTypeRuntimeError:
		return true
	case EventTypeRuntimeOutput:
		return true
	case EventTypeRuntimeStatus:
		return true
	case EventTypeSessionCheckpointed:
		return true
	case EventTypeSessionResumed:
		return true
	case EventTypeSessionStopped:
		return true
	case EventTypeToolCallCompleted:
		return true
	case EventTypeToolCallStarted:
		return true
	case EventTypeToolCallUpdated:
		return true
	case EventTypeTurnCompleted:
		return true
	case EventTypeTurnStarted:
		return true
	case EventTypeUsageRecorded:
		return true
	default:
		return false
	}
}

// AmaSessionEventType defines model for AmaSessionEventType.
type AmaSessionEventType string
