// Package sessionevent provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package sessionevent

// Defines values for AmaSessionEventType.
const (
	EventTypeAgentEnd            AmaSessionEventType = "agent_end"
	EventTypeAgentStart          AmaSessionEventType = "agent_start"
	EventTypeMessageEnd          AmaSessionEventType = "message_end"
	EventTypeMessageStart        AmaSessionEventType = "message_start"
	EventTypeMessageUpdate       AmaSessionEventType = "message_update"
	EventTypePermissionRequest   AmaSessionEventType = "permission.request"
	EventTypePolicyDecision      AmaSessionEventType = "policy.decision"
	EventTypeRunnerMetadata      AmaSessionEventType = "runner.metadata"
	EventTypeRuntimeError        AmaSessionEventType = "runtime.error"
	EventTypeRuntimeMetadata     AmaSessionEventType = "runtime.metadata"
	EventTypeRuntimeOutput       AmaSessionEventType = "runtime.output"
	EventTypeSessionCheckpoint   AmaSessionEventType = "session_checkpoint"
	EventTypeSessionResume       AmaSessionEventType = "session_resume"
	EventTypeSessionStop         AmaSessionEventType = "session_stop"
	EventTypeToolExecutionEnd    AmaSessionEventType = "tool_execution_end"
	EventTypeToolExecutionStart  AmaSessionEventType = "tool_execution_start"
	EventTypeToolExecutionUpdate AmaSessionEventType = "tool_execution_update"
	EventTypeTurnEnd             AmaSessionEventType = "turn_end"
	EventTypeTurnStart           AmaSessionEventType = "turn_start"
	EventTypeUsageRecorded       AmaSessionEventType = "usage.recorded"
)

// Valid indicates whether the value is a known member of the AmaSessionEventType enum.
func (e AmaSessionEventType) Valid() bool {
	switch e {
	case EventTypeAgentEnd:
		return true
	case EventTypeAgentStart:
		return true
	case EventTypeMessageEnd:
		return true
	case EventTypeMessageStart:
		return true
	case EventTypeMessageUpdate:
		return true
	case EventTypePermissionRequest:
		return true
	case EventTypePolicyDecision:
		return true
	case EventTypeRunnerMetadata:
		return true
	case EventTypeRuntimeError:
		return true
	case EventTypeRuntimeMetadata:
		return true
	case EventTypeRuntimeOutput:
		return true
	case EventTypeSessionCheckpoint:
		return true
	case EventTypeSessionResume:
		return true
	case EventTypeSessionStop:
		return true
	case EventTypeToolExecutionEnd:
		return true
	case EventTypeToolExecutionStart:
		return true
	case EventTypeToolExecutionUpdate:
		return true
	case EventTypeTurnEnd:
		return true
	case EventTypeTurnStart:
		return true
	case EventTypeUsageRecorded:
		return true
	default:
		return false
	}
}

// AmaSessionEventType defines model for AmaSessionEventType.
type AmaSessionEventType string
