// Package runtimebridge provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package runtimebridge

// Defines values for AmaSessionEventType.
const (
	EventTypeMessageCompleted    AmaSessionEventType = "message.completed"
	EventTypeMessageStarted      AmaSessionEventType = "message.started"
	EventTypeMessageUpdated      AmaSessionEventType = "message.updated"
	EventTypePermissionDenied    AmaSessionEventType = "permission.denied"
	EventTypePermissionRequested AmaSessionEventType = "permission.requested"
	EventTypePermissionResolved  AmaSessionEventType = "permission.resolved"
	EventTypeRuntimeCompleted    AmaSessionEventType = "runtime.completed"
	EventTypeRuntimeError        AmaSessionEventType = "runtime.error"
	EventTypeRuntimeStarted      AmaSessionEventType = "runtime.started"
	EventTypeTurnCompleted       AmaSessionEventType = "turn.completed"
	EventTypeTurnStarted         AmaSessionEventType = "turn.started"
	EventTypeUsageRecorded       AmaSessionEventType = "usage.recorded"
)

// Valid indicates whether the value is a known member of the AmaSessionEventType enum.
func (e AmaSessionEventType) Valid() bool {
	switch e {
	case EventTypeMessageCompleted:
		return true
	case EventTypeMessageStarted:
		return true
	case EventTypeMessageUpdated:
		return true
	case EventTypePermissionDenied:
		return true
	case EventTypePermissionRequested:
		return true
	case EventTypePermissionResolved:
		return true
	case EventTypeRuntimeCompleted:
		return true
	case EventTypeRuntimeError:
		return true
	case EventTypeRuntimeStarted:
		return true
	case EventTypeTurnCompleted:
		return true
	case EventTypeTurnStarted:
		return true
	case EventTypeUsageRecorded:
		return true
	default:
		return false
	}
}

// Defines values for ExternalRuntimeName.
const (
	ExternalRuntimeClaudeCode ExternalRuntimeName = "claude-code"
	ExternalRuntimeCodex      ExternalRuntimeName = "codex"
	ExternalRuntimeCopilot    ExternalRuntimeName = "copilot"
)

// Valid indicates whether the value is a known member of the ExternalRuntimeName enum.
func (e ExternalRuntimeName) Valid() bool {
	switch e {
	case ExternalRuntimeClaudeCode:
		return true
	case ExternalRuntimeCodex:
		return true
	case ExternalRuntimeCopilot:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeBridgeControlMessageType.
const (
	BridgeMessageTypeAbort              RuntimeBridgeControlMessageType = "abort"
	BridgeMessageTypePermissionDecision RuntimeBridgeControlMessageType = "permissionDecision"
	BridgeMessageTypeSend               RuntimeBridgeControlMessageType = "send"
)

// Valid indicates whether the value is a known member of the RuntimeBridgeControlMessageType enum.
func (e RuntimeBridgeControlMessageType) Valid() bool {
	switch e {
	case BridgeMessageTypeAbort:
		return true
	case BridgeMessageTypePermissionDecision:
		return true
	case BridgeMessageTypeSend:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeBridgeInventoryMessageType.
const (
	BridgeMessageTypeInventory RuntimeBridgeInventoryMessageType = "inventory"
)

// Valid indicates whether the value is a known member of the RuntimeBridgeInventoryMessageType enum.
func (e RuntimeBridgeInventoryMessageType) Valid() bool {
	switch e {
	case BridgeMessageTypeInventory:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeBridgeOutputMessageType.
const (
	BridgeMessageTypeError        RuntimeBridgeOutputMessageType = "error"
	BridgeMessageTypeReady        RuntimeBridgeOutputMessageType = "ready"
	BridgeMessageTypeResult       RuntimeBridgeOutputMessageType = "result"
	BridgeMessageTypeResumeToken  RuntimeBridgeOutputMessageType = "resumeToken"
	BridgeMessageTypeRuntimeEvent RuntimeBridgeOutputMessageType = "runtime.event"
)

// Valid indicates whether the value is a known member of the RuntimeBridgeOutputMessageType enum.
func (e RuntimeBridgeOutputMessageType) Valid() bool {
	switch e {
	case BridgeMessageTypeError:
		return true
	case BridgeMessageTypeReady:
		return true
	case BridgeMessageTypeResult:
		return true
	case BridgeMessageTypeResumeToken:
		return true
	case BridgeMessageTypeRuntimeEvent:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeBridgeRunMessageType.
const (
	BridgeMessageTypeRun RuntimeBridgeRunMessageType = "run"
)

// Valid indicates whether the value is a known member of the RuntimeBridgeRunMessageType enum.
func (e RuntimeBridgeRunMessageType) Valid() bool {
	switch e {
	case BridgeMessageTypeRun:
		return true
	default:
		return false
	}
}

// AmaSessionEventType defines model for AmaSessionEventType.
type AmaSessionEventType string

// ExternalRuntimeName defines model for ExternalRuntimeName.
type ExternalRuntimeName string

// JSON defines model for JSON.
type JSON map[string]interface{}

// RuntimeBridgeControlMessage defines model for RuntimeBridgeControlMessage.
type RuntimeBridgeControlMessage struct {
	Allowed      bool                            `json:"allowed,omitempty"`
	Message      string                          `json:"message,omitempty"`
	PermissionID string                          `json:"permissionId,omitempty"`
	Reason       string                          `json:"reason,omitempty"`
	RequestID    string                          `json:"requestId"`
	Type         RuntimeBridgeControlMessageType `json:"type"`
}

// RuntimeBridgeControlMessageType defines model for RuntimeBridgeControlMessage.Type.
type RuntimeBridgeControlMessageType string

// RuntimeBridgeError defines model for RuntimeBridgeError.
type RuntimeBridgeError struct {
	Code    string      `json:"code,omitempty"`
	Details interface{} `json:"details,omitempty"`
	Message string      `json:"message"`
}

// RuntimeBridgeInventoryMessage defines model for RuntimeBridgeInventoryMessage.
type RuntimeBridgeInventoryMessage struct {
	Env          map[string]string                 `json:"env"`
	IncludeUsage bool                              `json:"includeUsage,omitempty"`
	RequestID    string                            `json:"requestId"`
	Type         RuntimeBridgeInventoryMessageType `json:"type"`
}

// RuntimeBridgeInventoryMessageType defines model for RuntimeBridgeInventoryMessage.Type.
type RuntimeBridgeInventoryMessageType string

// RuntimeBridgeInventoryResult defines model for RuntimeBridgeInventoryResult.
type RuntimeBridgeInventoryResult struct {
	Runtimes []RuntimeBridgeInventoryRuntime `json:"runtimes"`
}

// RuntimeBridgeInventoryRuntime defines model for RuntimeBridgeInventoryRuntime.
type RuntimeBridgeInventoryRuntime struct {
	Binary         string                     `json:"binary"`
	Detail         string                     `json:"detail"`
	FallbackModels []string                   `json:"fallbackModels"`
	Installed      bool                       `json:"installed"`
	LimitedDetail  string                     `json:"limitedDetail,omitempty"`
	Models         []string                   `json:"models"`
	Runtime        ExternalRuntimeName        `json:"runtime"`
	Status         string                     `json:"status"`
	UsageWindows   []RuntimeBridgeUsageWindow `json:"usageWindows,omitempty"`
	Version        string                     `json:"version,omitempty"`
}

// RuntimeBridgeOutputMessage defines model for RuntimeBridgeOutputMessage.
type RuntimeBridgeOutputMessage struct {
	Error       RuntimeBridgeError             `json:"error,omitempty"`
	Event       JSON                           `json:"event,omitempty"`
	RequestID   string                         `json:"requestId,omitempty"`
	Result      JSON                           `json:"result,omitempty"`
	ResumeToken string                         `json:"resumeToken,omitempty"`
	Type        RuntimeBridgeOutputMessageType `json:"type"`
}

// RuntimeBridgeOutputMessageType defines model for RuntimeBridgeOutputMessage.Type.
type RuntimeBridgeOutputMessageType string

// RuntimeBridgeRunMessage defines model for RuntimeBridgeRunMessage.
type RuntimeBridgeRunMessage struct {
	AgentSnapshot JSON                        `json:"agentSnapshot,omitempty"`
	Cwd           string                      `json:"cwd"`
	Env           map[string]string           `json:"env"`
	Model         string                      `json:"model,omitempty"`
	Prompt        string                      `json:"prompt"`
	Provider      string                      `json:"provider,omitempty"`
	RequestID     string                      `json:"requestId"`
	Resume        bool                        `json:"resume,omitempty"`
	ResumeToken   string                      `json:"resumeToken,omitempty"`
	Runtime       ExternalRuntimeName         `json:"runtime"`
	RuntimeConfig JSON                        `json:"runtimeConfig,omitempty"`
	SessionID     string                      `json:"sessionId"`
	Type          RuntimeBridgeRunMessageType `json:"type"`
}

// RuntimeBridgeRunMessageType defines model for RuntimeBridgeRunMessage.Type.
type RuntimeBridgeRunMessageType string

// RuntimeBridgeUsageWindow defines model for RuntimeBridgeUsageWindow.
type RuntimeBridgeUsageWindow struct {
	Label       string  `json:"label"`
	ResetsAt    string  `json:"resetsAt"`
	Utilization float32 `json:"utilization"`
}
