// Package runtimebridge provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package runtimebridge

// Defines values for AmaSessionEventType.
const (
	EventTypeAgentEnd            AmaSessionEventType = "agent_end"
	EventTypeAgentStart          AmaSessionEventType = "agent_start"
	EventTypeMessageEnd          AmaSessionEventType = "message_end"
	EventTypeMessageStart        AmaSessionEventType = "message_start"
	EventTypeMessageUpdate       AmaSessionEventType = "message_update"
	EventTypePermissionRequest   AmaSessionEventType = "permission.request"
	EventTypePolicyDecision      AmaSessionEventType = "policy.decision"
	EventTypeRunnerMetadata      AmaSessionEventType = "runner.metadata"
	EventTypeRuntimeError        AmaSessionEventType = "runtime.error"
	EventTypeRuntimeMetadata     AmaSessionEventType = "runtime.metadata"
	EventTypeRuntimeOutput       AmaSessionEventType = "runtime.output"
	EventTypeSessionCheckpoint   AmaSessionEventType = "session_checkpoint"
	EventTypeSessionResume       AmaSessionEventType = "session_resume"
	EventTypeSessionStop         AmaSessionEventType = "session_stop"
	EventTypeToolExecutionEnd    AmaSessionEventType = "tool_execution_end"
	EventTypeToolExecutionStart  AmaSessionEventType = "tool_execution_start"
	EventTypeToolExecutionUpdate AmaSessionEventType = "tool_execution_update"
	EventTypeTurnEnd             AmaSessionEventType = "turn_end"
	EventTypeTurnStart           AmaSessionEventType = "turn_start"
	EventTypeUsageRecorded       AmaSessionEventType = "usage.recorded"
)

// Valid indicates whether the value is a known member of the AmaSessionEventType enum.
func (e AmaSessionEventType) Valid() bool {
	switch e {
	case EventTypeAgentEnd:
		return true
	case EventTypeAgentStart:
		return true
	case EventTypeMessageEnd:
		return true
	case EventTypeMessageStart:
		return true
	case EventTypeMessageUpdate:
		return true
	case EventTypePermissionRequest:
		return true
	case EventTypePolicyDecision:
		return true
	case EventTypeRunnerMetadata:
		return true
	case EventTypeRuntimeError:
		return true
	case EventTypeRuntimeMetadata:
		return true
	case EventTypeRuntimeOutput:
		return true
	case EventTypeSessionCheckpoint:
		return true
	case EventTypeSessionResume:
		return true
	case EventTypeSessionStop:
		return true
	case EventTypeToolExecutionEnd:
		return true
	case EventTypeToolExecutionStart:
		return true
	case EventTypeToolExecutionUpdate:
		return true
	case EventTypeTurnEnd:
		return true
	case EventTypeTurnStart:
		return true
	case EventTypeUsageRecorded:
		return true
	default:
		return false
	}
}

// Defines values for BridgeControlType.
const (
	BridgeMessageTypeAbort              BridgeControlType = "abort"
	BridgeMessageTypePermissionDecision BridgeControlType = "permissionDecision"
	BridgeMessageTypeSend               BridgeControlType = "send"
)

// Valid indicates whether the value is a known member of the BridgeControlType enum.
func (e BridgeControlType) Valid() bool {
	switch e {
	case BridgeMessageTypeAbort:
		return true
	case BridgeMessageTypePermissionDecision:
		return true
	case BridgeMessageTypeSend:
		return true
	default:
		return false
	}
}

// Defines values for BridgeInventoryRequestType.
const (
	BridgeMessageTypeInventory BridgeInventoryRequestType = "inventory"
)

// Valid indicates whether the value is a known member of the BridgeInventoryRequestType enum.
func (e BridgeInventoryRequestType) Valid() bool {
	switch e {
	case BridgeMessageTypeInventory:
		return true
	default:
		return false
	}
}

// Defines values for BridgeOutputType.
const (
	BridgeMessageTypeError        BridgeOutputType = "error"
	BridgeMessageTypeReady        BridgeOutputType = "ready"
	BridgeMessageTypeResult       BridgeOutputType = "result"
	BridgeMessageTypeResumeToken  BridgeOutputType = "resumeToken"
	BridgeMessageTypeSessionEvent BridgeOutputType = "sessionEvent"
)

// Valid indicates whether the value is a known member of the BridgeOutputType enum.
func (e BridgeOutputType) Valid() bool {
	switch e {
	case BridgeMessageTypeError:
		return true
	case BridgeMessageTypeReady:
		return true
	case BridgeMessageTypeResult:
		return true
	case BridgeMessageTypeResumeToken:
		return true
	case BridgeMessageTypeSessionEvent:
		return true
	default:
		return false
	}
}

// Defines values for BridgeRunRequestType.
const (
	BridgeMessageTypeRun BridgeRunRequestType = "run"
)

// Valid indicates whether the value is a known member of the BridgeRunRequestType enum.
func (e BridgeRunRequestType) Valid() bool {
	switch e {
	case BridgeMessageTypeRun:
		return true
	default:
		return false
	}
}

// Defines values for ExternalRuntimeName.
const (
	ExternalRuntimeClaudeCode ExternalRuntimeName = "claude-code"
	ExternalRuntimeCodex      ExternalRuntimeName = "codex"
	ExternalRuntimeCopilot    ExternalRuntimeName = "copilot"
)

// Valid indicates whether the value is a known member of the ExternalRuntimeName enum.
func (e ExternalRuntimeName) Valid() bool {
	switch e {
	case ExternalRuntimeClaudeCode:
		return true
	case ExternalRuntimeCodex:
		return true
	case ExternalRuntimeCopilot:
		return true
	default:
		return false
	}
}

// AmaSessionEventType defines model for AmaSessionEventType.
type AmaSessionEventType string

// BridgeControl defines model for BridgeControl.
type BridgeControl struct {
	Allowed      bool              `json:"allowed,omitempty"`
	Message      string            `json:"message,omitempty"`
	PermissionID string            `json:"permissionId,omitempty"`
	Reason       string            `json:"reason,omitempty"`
	RequestID    string            `json:"requestId"`
	Type         BridgeControlType `json:"type"`
}

// BridgeControlType defines model for BridgeControl.Type.
type BridgeControlType string

// BridgeError defines model for BridgeError.
type BridgeError struct {
	Code    string      `json:"code,omitempty"`
	Details interface{} `json:"details,omitempty"`
	Message string      `json:"message"`
}

// BridgeInventoryRequest defines model for BridgeInventoryRequest.
type BridgeInventoryRequest struct {
	Env          map[string]string          `json:"env"`
	IncludeUsage bool                       `json:"includeUsage,omitempty"`
	RequestID    string                     `json:"requestId"`
	Type         BridgeInventoryRequestType `json:"type"`
}

// BridgeInventoryRequestType defines model for BridgeInventoryRequest.Type.
type BridgeInventoryRequestType string

// BridgeInventoryResult defines model for BridgeInventoryResult.
type BridgeInventoryResult struct {
	Runtimes []BridgeInventoryRuntime `json:"runtimes"`
}

// BridgeInventoryRuntime defines model for BridgeInventoryRuntime.
type BridgeInventoryRuntime struct {
	Binary         string              `json:"binary"`
	Detail         string              `json:"detail"`
	FallbackModels []string            `json:"fallbackModels"`
	Installed      bool                `json:"installed"`
	LimitedDetail  string              `json:"limitedDetail,omitempty"`
	Models         []string            `json:"models"`
	Runtime        ExternalRuntimeName `json:"runtime"`
	Status         string              `json:"status"`
	UsageWindows   []BridgeUsageWindow `json:"usageWindows,omitempty"`
	Version        string              `json:"version,omitempty"`
}

// BridgeOutput defines model for BridgeOutput.
type BridgeOutput struct {
	Error       BridgeError         `json:"error,omitempty"`
	EventType   AmaSessionEventType `json:"eventType,omitempty"`
	Metadata    JSON                `json:"metadata,omitempty"`
	Payload     JSON                `json:"payload,omitempty"`
	RequestID   string              `json:"requestId,omitempty"`
	Result      JSON                `json:"result,omitempty"`
	ResumeToken string              `json:"resumeToken,omitempty"`
	Type        BridgeOutputType    `json:"type"`
}

// BridgeOutputType defines model for BridgeOutput.Type.
type BridgeOutputType string

// BridgeRunRequest defines model for BridgeRunRequest.
type BridgeRunRequest struct {
	AgentSnapshot JSON                 `json:"agentSnapshot,omitempty"`
	Cwd           string               `json:"cwd"`
	Env           map[string]string    `json:"env"`
	Model         string               `json:"model,omitempty"`
	Prompt        string               `json:"prompt"`
	Provider      string               `json:"provider,omitempty"`
	RequestID     string               `json:"requestId"`
	Resume        bool                 `json:"resume,omitempty"`
	ResumeToken   string               `json:"resumeToken,omitempty"`
	Runtime       ExternalRuntimeName  `json:"runtime"`
	RuntimeConfig JSON                 `json:"runtimeConfig,omitempty"`
	SessionID     string               `json:"sessionId"`
	Type          BridgeRunRequestType `json:"type"`
}

// BridgeRunRequestType defines model for BridgeRunRequest.Type.
type BridgeRunRequestType string

// BridgeUsageWindow defines model for BridgeUsageWindow.
type BridgeUsageWindow struct {
	Label       string  `json:"label"`
	ResetsAt    string  `json:"resetsAt"`
	Utilization float32 `json:"utilization"`
}

// ExternalRuntimeName defines model for ExternalRuntimeName.
type ExternalRuntimeName string

// JSON defines model for JSON.
type JSON map[string]interface{}
