import { execFileSync } from 'node:child_process'
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { AMA_SESSION_EVENT_DEFINITIONS } from '../shared/session-events'

// Single-sources the canonical AMA session event-type vocabulary into the Go
// runner. shared/session-events.ts is the one source of truth; the runner emits
// only these type strings, so generating them (instead of hand-copying magic
// strings into runner.go) makes TS↔Go drift a CI failure rather than a silent
// runtime bug. Mirrors the openapi:generate / openapi:check governance pair.
const HEADER = '// Code generated by `pnpm run contract:generate`; DO NOT EDIT.'
const OUTPUT = path.join(process.cwd(), 'cmd', 'ama-runner', 'contract_gen.go')

function goConstName(eventType: string): string {
  return eventType
    .split(/[._]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

function render(): string {
  const types = Object.keys(AMA_SESSION_EVENT_DEFINITIONS)
  const lines: string[] = [
    HEADER,
    '//',
    '// Canonical AMA session event types, single-sourced from',
    '// shared/session-events.ts (AMA_SESSION_EVENT_DEFINITIONS).',
    '',
    'package main',
    '',
    'const (',
    ...types.map((type) => `\tEventType${goConstName(type)} = ${JSON.stringify(type)}`),
    ')',
    '',
    '// CanonicalEventTypes is the full ordered set of canonical event types.',
    'var CanonicalEventTypes = []string{',
    ...types.map((type) => `\tEventType${goConstName(type)},`),
    '}',
    '',
    '// IsCanonicalEventType reports whether t is a known canonical event type.',
    'func IsCanonicalEventType(t string) bool {',
    '\tfor _, known := range CanonicalEventTypes {',
    '\t\tif known == t {',
    '\t\t\treturn true',
    '\t\t}',
    '\t}',
    '\treturn false',
    '}',
    '',
  ]
  return lines.join('\n')
}

// gofmt the rendered source so the committed file matches `go fmt` and
// contract:check stays byte-stable. Falls back to the raw render when the Go
// toolchain is absent (e.g. a TS-only CI lane).
function gofmt(source: string): string {
  try {
    return execFileSync('gofmt', [], { input: source, encoding: 'utf8' })
  } catch {
    return source
  }
}

async function main() {
  const content = gofmt(render())
  if (process.argv.includes('--check')) {
    const existing = await readFile(OUTPUT, 'utf8').catch(() => '')
    if (existing !== content) {
      console.error('cmd/ama-runner/contract_gen.go is out of date. Run: pnpm run contract:generate')
      process.exit(1)
    }
    console.log('contract_gen.go is up to date.')
    return
  }
  await writeFile(OUTPUT, content)
  console.log(
    `Generated ${path.relative(process.cwd(), OUTPUT)} (${Object.keys(AMA_SESSION_EVENT_DEFINITIONS).length} event types).`,
  )
}

main()
