import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { createApp } from '../server/app'
import type { Env } from '../server/env'

type OpenApiOperation = {
  operationId?: string
  summary?: string
  tags?: string[]
}

type OpenApiDocument = {
  openapi: string
  paths: Record<string, Record<string, OpenApiOperation>>
}

type GeneratedOperation = {
  method: string
  path: string
  operationId: string
  summary: string
  tags: string[]
}

const GENERATED_HEADER = 'Code generated by pnpm run openapi:generate; DO NOT EDIT.'
const HTTP_METHODS = new Set(['get', 'post', 'put', 'patch', 'delete'])

async function main() {
  const document = await routeGeneratedOpenApi()
  const operations = generatedOperations(document)
  const outputs = new Map<string, string>([
    ['sdk/openapi.json', jsonContent(document)],
    [
      'sdk/typescript/src/generated/operations.ts',
      `// ${GENERATED_HEADER}

export const operations = ${JSON.stringify(operations, null, 2)} as const

export type AmaOperationId = (typeof operations)[number]['operationId']
`,
    ],
    [
      'sdk/go/ama/operations_gen.go',
      `// ${GENERATED_HEADER}

package ama

type Operation struct {
\tMethod      string
\tPath        string
\tOperationID string
\tSummary     string
\tTags        []string
}

var Operations = []Operation{
${operations.map((operation) => goOperation(operation)).join('\n')}
}
`,
    ],
    [
      'sdk/python/ama_sdk/operations.py',
      `# ${GENERATED_HEADER}

OPERATIONS = ${pythonLiteral(operations)}
`,
    ],
  ])

  if (process.argv.includes('--check')) {
    await checkOutputs(outputs)
    return
  }

  for (const [filePath, content] of outputs) {
    await writeOutput(filePath, content)
  }
}

async function routeGeneratedOpenApi() {
  const app = createApp()
  const response = await app.fetch(new Request('https://example.test/api/v1/openapi.json'), {} as Env)
  if (!response.ok) {
    throw new Error(`OpenAPI generation failed with HTTP ${response.status}`)
  }
  return (await response.json()) as OpenApiDocument
}

function generatedOperations(document: OpenApiDocument) {
  return Object.entries(document.paths)
    .flatMap(([apiPath, methods]) =>
      Object.entries(methods)
        .filter(([method]) => HTTP_METHODS.has(method))
        .map(([method, operation]) => {
          if (!operation.operationId) {
            throw new Error(`${method.toUpperCase()} ${apiPath} is missing operationId`)
          }
          return {
            method: method.toUpperCase(),
            path: apiPath,
            operationId: operation.operationId,
            summary: operation.summary ?? '',
            tags: operation.tags ?? [],
          }
        }),
    )
    .sort((left, right) => left.operationId.localeCompare(right.operationId))
}

function jsonContent(value: unknown) {
  return `${JSON.stringify(value, null, 2)}\n`
}

async function writeOutput(filePath: string, content: string) {
  await mkdir(path.dirname(filePath), { recursive: true })
  await writeFile(filePath, content)
}

async function checkOutputs(outputs: Map<string, string>) {
  const staleFiles: string[] = []
  for (const [filePath, expected] of outputs) {
    let actual: string
    try {
      actual = await readFile(filePath, 'utf8')
    } catch {
      staleFiles.push(filePath)
      continue
    }
    if (actual !== expected) {
      staleFiles.push(filePath)
    }
  }
  if (staleFiles.length > 0) {
    throw new Error(`Generated SDK artifacts are stale. Run pnpm run openapi:generate.\n${staleFiles.join('\n')}`)
  }
}

function goOperation(operation: GeneratedOperation) {
  return `\t{Method: ${goString(operation.method)}, Path: ${goString(operation.path)}, OperationID: ${goString(
    operation.operationId,
  )}, Summary: ${goString(operation.summary)}, Tags: []string{${operation.tags.map(goString).join(', ')}}},`
}

function goString(value: string) {
  return JSON.stringify(value)
}

function pythonLiteral(value: unknown) {
  return JSON.stringify(value, null, 2)
    .replaceAll(': true', ': True')
    .replaceAll(': false', ': False')
    .replaceAll(': null', ': None')
}

await main()
